import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { TIBIA_SPELL_CATALOG } from "./tibia-spell-catalog.generated.js";
import { CURATED_MYSTERY_KNOWLEDGE, CURATED_WHEEL_KNOWLEDGE, fetchTibiaGeneralKnowledge, OFFICIAL_MECHANIC_KNOWLEDGE, officialRuneEntries, USER_TAUGHT_KNOWLEDGE } from "./tibia-general-knowledge.js";
import { fetchTibiaNpcDialogueKnowledge } from "./tibia-npc-dialogues.js";
import { fetchTibiaBookKnowledge } from "./tibia-books.js";
import { TIBIA_GENERAL_KNOWLEDGE } from "./tibia-general-knowledge.generated.js";
import { huntingProfile, type TibiaKnowledgeEntry } from "./tibia-general-knowledge.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(currentDir, "tibia-general-knowledge.generated.ts");

async function main(): Promise<void> {
  const reuse = process.argv.includes("--reuse-existing");
  const existing = TIBIA_GENERAL_KNOWLEDGE as unknown as readonly TibiaKnowledgeEntry[];
  const base: readonly TibiaKnowledgeEntry[] = reuse
    ? existing.filter((entry) => entry.domain !== "rune" && entry.domain !== "wheel").map((entry) => entry.domain === "hunting-place"
      ? { ...entry, metadata: { ...entry.metadata, huntingProfile: huntingProfile(entry.metadata as Record<string, unknown>) } }
      : entry)
    : await fullKnowledge();
  const entries = [...base, ...officialRuneEntries(TIBIA_SPELL_CATALOG), ...CURATED_WHEEL_KNOWLEDGE]
    .sort((left, right) => left.domain.localeCompare(right.domain) || left.name.localeCompare(right.name));
  const generated = [
    "// Generated by npm run knowledge:sync:tibia. Do not edit manually.",
    'import type { TibiaKnowledgeEntry } from "./tibia-general-knowledge.js";',
    "",
    `export const TIBIA_GENERAL_KNOWLEDGE = ${JSON.stringify(entries, null, 2)} as const satisfies readonly TibiaKnowledgeEntry[];`,
    ""
  ].join("\n");
  await writeFile(outputPath, generated, "utf8");
  const counts = entries.reduce<Record<string, number>>((result, entry) => {
    result[entry.domain] = (result[entry.domain] ?? 0) + 1;
    return result;
  }, {});
  console.log(`Saved ${entries.length} Tibia knowledge records.`);
  console.log(counts);
}

async function fullKnowledge() {
  const [community, dialogues, books] = await Promise.all([fetchTibiaGeneralKnowledge(), fetchTibiaNpcDialogueKnowledge(), fetchTibiaBookKnowledge()]);
  return [...community, ...dialogues, ...books, ...OFFICIAL_MECHANIC_KNOWLEDGE, ...USER_TAUGHT_KNOWLEDGE, ...CURATED_MYSTERY_KNOWLEDGE];
}

await main();
