import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { enrichCreature, fetchOfficialCreatureCatalog, fetchTibiaItemCatalog, normalizeCreatureName, type TibiaCreatureCatalogEntry } from "./tibia-game-catalog.js";
import { TIBIA_CREATURE_CATALOG as EXISTING_CREATURES } from "./tibia-creature-catalog.generated.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const generatedAt = new Date().toISOString();
const requested = new Set(process.argv.slice(2));
const syncCreatures = requested.size === 0 || requested.has("--creatures-only");
const syncItems = requested.size === 0 || requested.has("--items-only");

if (syncCreatures) {
  const creatures = requested.has("--reuse-existing") ? await enrichExistingCreatures() : await fetchOfficialCreatureCatalog();
  await writeGeneratedFile(
    "tibia-creature-catalog.generated.ts",
    "TibiaCreatureCatalogEntry",
    "TIBIA_CREATURE_CATALOG",
    "TIBIA_CREATURE_CATALOG_GENERATED_AT",
    "TIBIA_CREATURE_CATALOG_SOURCE",
    "https://api.tibiadata.com/v4/creatures",
    creatures
  );
  console.log(`Saved ${creatures.length} official Tibia creatures.`);
}

async function enrichExistingCreatures(): Promise<readonly TibiaCreatureCatalogEntry[]> {
  const first = await (await fetch("https://tibiadata.bytewizards.de/api/v1/creatures?page=1&pageSize=100")).json() as { totalCount: number; items: Array<{ id: number; name: string }> };
  const pages = await Promise.all(Array.from({ length: Math.ceil(first.totalCount / 100) - 1 }, async (_, index) =>
    await (await fetch(`https://tibiadata.bytewizards.de/api/v1/creatures?page=${index + 2}&pageSize=100`)).json() as { items: Array<{ id: number; name: string }> }));
  const ids = new Map([first, ...pages].flatMap((page) => page.items).map((entry) => [normalizeCreatureName(entry.name), entry.id]));
  const result: TibiaCreatureCatalogEntry[] = new Array(EXISTING_CREATURES.length);
  let cursor = 0;
  await Promise.all(Array.from({ length: 12 }, async () => {
    while (cursor < EXISTING_CREATURES.length) {
      const index = cursor++;
      const creature = EXISTING_CREATURES[index]! as unknown as TibiaCreatureCatalogEntry;
      try {
        const id = ids.get(normalizeCreatureName(creature.race)) ?? ids.get(normalizeCreatureName(creature.name));
        const response = await fetch(`https://tibiadata.bytewizards.de/api/v1/creatures/${encodeURIComponent(id ?? creature.race)}`);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        result[index] = enrichCreature(creature, await response.json(), creature.race);
      } catch {
        // The existing catalog predates the taxonomy fields, so they are spelled out
        // here instead of relying on the spread to carry them in as undefined.
        result[index] = {
          ...creature,
          creatureClass: creature.creatureClass ?? null,
          bestiaryClass: creature.bestiaryClass ?? null,
          bestiaryDifficulty: creature.bestiaryDifficulty ?? null,
          bestiaryOccurrence: creature.bestiaryOccurrence ?? null,
          armor: 0, mitigation: 0, maxDamage: 0, damageByType: {}, damageModifiers: {},
          attacks: [], location: "", lootDetails: [], communitySourceUrl: null, communitySourceUpdatedAt: null
        };
      }
    }
  }));
  return result;
}

if (syncItems) {
  const items = await fetchTibiaItemCatalog();
  await writeGeneratedFile(
    "tibia-item-catalog.generated.ts",
    "TibiaItemCatalogEntry",
    "TIBIA_ITEM_CATALOG",
    "TIBIA_ITEM_CATALOG_GENERATED_AT",
    "TIBIA_ITEM_CATALOG_SOURCE",
    "https://tibiadata.bytewizards.de/api/v1/items",
    items
  );
  console.log(`Saved ${items.length} TibiaWiki item records.`);
}

async function writeGeneratedFile(
  filename: string,
  typeName: string,
  constantName: string,
  generatedAtName: string,
  sourceName: string,
  sourceUrl: string,
  data: unknown
): Promise<void> {
  const source = `// Generated by npm run catalog:sync. Do not edit manually.\n` +
    `// Source: ${sourceUrl}\n` +
    `// Generated at: ${generatedAt}\n` +
    `import type { ${typeName} } from "./tibia-game-catalog.js";\n\n` +
    `export const ${generatedAtName} = ${JSON.stringify(generatedAt)};\n` +
    `export const ${sourceName} = ${JSON.stringify(sourceUrl)};\n` +
    `export const ${constantName} = ${JSON.stringify(data, null, 2)} as const satisfies readonly ${typeName}[];\n`;
  await writeFile(resolve(currentDir, filename), source, "utf8");
}
