import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { TIBIA_SPELL_CATALOG } from "./tibia-spell-catalog.generated.js";
import { fetchTibiaGeneralKnowledge, OFFICIAL_MECHANIC_KNOWLEDGE, officialRuneEntries, USER_TAUGHT_KNOWLEDGE } from "./tibia-general-knowledge.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(currentDir, "tibia-general-knowledge.generated.ts");

async function main(): Promise<void> {
  const community = await fetchTibiaGeneralKnowledge();
  const entries = [...community, ...officialRuneEntries(TIBIA_SPELL_CATALOG), ...OFFICIAL_MECHANIC_KNOWLEDGE, ...USER_TAUGHT_KNOWLEDGE]
    .sort((left, right) => left.domain.localeCompare(right.domain) || left.name.localeCompare(right.name));
  const generated = [
    "// Generated by npm run knowledge:sync:tibia. Do not edit manually.",
    'import type { TibiaKnowledgeEntry } from "./tibia-general-knowledge.js";',
    "",
    `export const TIBIA_GENERAL_KNOWLEDGE = ${JSON.stringify(entries, null, 2)} as const satisfies readonly TibiaKnowledgeEntry[];`,
    ""
  ].join("\n");
  await writeFile(outputPath, generated, "utf8");
  const counts = entries.reduce<Record<string, number>>((result, entry) => {
    result[entry.domain] = (result[entry.domain] ?? 0) + 1;
    return result;
  }, {});
  console.log(`Saved ${entries.length} Tibia knowledge records.`);
  console.log(counts);
}

await main();
