import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchOfficialCreatureCatalog, fetchTibiaItemCatalog } from "./tibia-game-catalog.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const generatedAt = new Date().toISOString();
const requested = new Set(process.argv.slice(2));
const syncCreatures = requested.size === 0 || requested.has("--creatures-only");
const syncItems = requested.size === 0 || requested.has("--items-only");

if (syncCreatures) {
  const creatures = await fetchOfficialCreatureCatalog();
  await writeGeneratedFile(
    "tibia-creature-catalog.generated.ts",
    "TibiaCreatureCatalogEntry",
    "TIBIA_CREATURE_CATALOG",
    "TIBIA_CREATURE_CATALOG_GENERATED_AT",
    "TIBIA_CREATURE_CATALOG_SOURCE",
    "https://api.tibiadata.com/v4/creatures",
    creatures
  );
  console.log(`Saved ${creatures.length} official Tibia creatures.`);
}

if (syncItems) {
  const items = await fetchTibiaItemCatalog();
  await writeGeneratedFile(
    "tibia-item-catalog.generated.ts",
    "TibiaItemCatalogEntry",
    "TIBIA_ITEM_CATALOG",
    "TIBIA_ITEM_CATALOG_GENERATED_AT",
    "TIBIA_ITEM_CATALOG_SOURCE",
    "https://tibiadata.bytewizards.de/api/v1/items",
    items
  );
  console.log(`Saved ${items.length} TibiaWiki item records.`);
}

async function writeGeneratedFile(
  filename: string,
  typeName: string,
  constantName: string,
  generatedAtName: string,
  sourceName: string,
  sourceUrl: string,
  data: unknown
): Promise<void> {
  const source = `// Generated by npm run catalog:sync. Do not edit manually.\n` +
    `// Source: ${sourceUrl}\n` +
    `// Generated at: ${generatedAt}\n` +
    `import type { ${typeName} } from "./tibia-game-catalog.js";\n\n` +
    `export const ${generatedAtName} = ${JSON.stringify(generatedAt)};\n` +
    `export const ${sourceName} = ${JSON.stringify(sourceUrl)};\n` +
    `export const ${constantName} = ${JSON.stringify(data, null, 2)} as const satisfies readonly ${typeName}[];\n`;
  await writeFile(resolve(currentDir, filename), source, "utf8");
}
