import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchOfficialSpellCatalog } from "./tibia-spell-catalog.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(currentDir, "tibia-spell-catalog.generated.ts");

const spells = await fetchOfficialSpellCatalog();
const generatedAt = new Date().toISOString();
const sourceUrl = "https://www.tibia.com/library/?subtopic=spells";
const source = `// Generated by npm run skills:sync. Do not edit manually.\n` +
  `// Official source: ${sourceUrl}\n` +
  `// Generated at: ${generatedAt}\n` +
  `import type { TibiaSpellCatalogEntry } from "./tibia-spell-catalog.js";\n\n` +
  `export const TIBIA_SPELL_CATALOG_GENERATED_AT = ${JSON.stringify(generatedAt)};\n` +
  `export const TIBIA_SPELL_CATALOG_SOURCE = ${JSON.stringify(sourceUrl)};\n` +
  `export const TIBIA_SPELL_CATALOG = ${JSON.stringify(spells, null, 2)} as const satisfies readonly TibiaSpellCatalogEntry[];\n`;

await writeFile(outputPath, source, "utf8");
console.log(`Saved ${spells.length} official Tibia spells to ${outputPath}.`);
