import { spawn } from "node:child_process";
import { readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchTibiaBookKnowledge } from "./tibia-books.js";
import type { TibiaBookTranslation } from "./tibia-book-translations.generated.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(currentDir, "../..");
const outputPath = resolve(currentDir, "tibia-book-translations.generated.ts");
const inputPath = resolve(tmpdir(), "botzin-tibia-book-translation-input.json");
const cachePath = resolve(tmpdir(), "botzin-tibia-book-translation-cache.json");

async function main(): Promise<void> {
  const books = await fetchTibiaBookKnowledge();
  const inputs = books.map((book) => ({
    pageId: book.key.split(":").at(-1),
    revisionId: book.metadata.revisionId,
    titleEn: book.metadata.titleEn,
    blurbEn: book.metadata.blurbEn,
    textEn: book.metadata.textEn
  }));
  await writeFile(inputPath, JSON.stringify(inputs), "utf8");
  const [versioned, temporary] = await Promise.all([currentCache(), jsonCache(cachePath)]);
  await writeFile(cachePath, JSON.stringify({ ...versioned, ...temporary }), "utf8");
  const python = process.env.BOTZIN_ARGOS_PYTHON || "python";
  await run(python, [resolve(projectRoot, "scripts/translate-tibia-books.py"), inputPath, cachePath]);
  const translations = JSON.parse(await readFile(cachePath, "utf8")) as Record<string, TibiaBookTranslation>;
  const generated = [
    "// Generated by npm run books:translate. Do not edit manually.",
    "",
    "export interface TibiaBookTranslation {",
    "  readonly revisionId: number | null;",
    "  readonly titlePtBr: string;",
    "  readonly blurbPtBr: string;",
    "  readonly textPtBr: string;",
    "  readonly provider: string;",
    "  readonly generatedAt: string;",
    "}",
    "",
    `export const TIBIA_BOOK_TRANSLATIONS: Readonly<Record<string, TibiaBookTranslation>> = ${JSON.stringify(translations, null, 2)};`,
    ""
  ].join("\n");
  await writeFile(outputPath, generated, "utf8");
  await Promise.all([rm(inputPath, { force: true }), rm(cachePath, { force: true })]);
  console.log(`Saved ${Object.keys(translations).length} PT-BR book translations.`);
}

async function jsonCache(path: string): Promise<Record<string, TibiaBookTranslation>> {
  try {
    return JSON.parse(await readFile(path, "utf8")) as Record<string, TibiaBookTranslation>;
  } catch {
    return {};
  }
}

async function currentCache(): Promise<Record<string, TibiaBookTranslation>> {
  try {
    const source = await readFile(outputPath, "utf8");
    const match = source.match(/TIBIA_BOOK_TRANSLATIONS\s*=\s*(\{[\s\S]*\})\s+as const/);
    return match ? JSON.parse(match[1]!) as Record<string, TibiaBookTranslation> : {};
  } catch {
    return {};
  }
}

function run(command: string, args: string[]): Promise<void> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, { stdio: "inherit" });
    child.once("error", reject);
    child.once("exit", (code) => code === 0 ? resolvePromise() : reject(new Error(`Translator exited with code ${code}.`)));
  });
}

await main();
