import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchOfficialSpellCatalog, parseCommunitySpellDetail } from "./tibia-spell-catalog.js";
import { TIBIA_SPELL_CATALOG as EXISTING_SPELLS } from "./tibia-spell-catalog.generated.js";

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(currentDir, "tibia-spell-catalog.generated.ts");

const spells = process.argv.includes("--reuse-existing") ? await enrichExistingRunes() : await fetchOfficialSpellCatalog();
const generatedAt = new Date().toISOString();
const sourceUrl = "https://www.tibia.com/library/?subtopic=spells";
const source = `// Generated by npm run skills:sync. Do not edit manually.\n` +
  `// Official source: ${sourceUrl}\n` +
  `// Generated at: ${generatedAt}\n` +
  `import type { TibiaSpellCatalogEntry } from "./tibia-spell-catalog.js";\n\n` +
  `export const TIBIA_SPELL_CATALOG_GENERATED_AT = ${JSON.stringify(generatedAt)};\n` +
  `export const TIBIA_SPELL_CATALOG_SOURCE = ${JSON.stringify(sourceUrl)};\n` +
  `export const TIBIA_SPELL_CATALOG = ${JSON.stringify(spells, null, 2)} as const satisfies readonly TibiaSpellCatalogEntry[];\n`;

await writeFile(outputPath, source, "utf8");
console.log(`Saved ${spells.length} official Tibia spells to ${outputPath}.`);

async function enrichExistingRunes() {
  const list = await (await fetch("https://tibiadata.bytewizards.de/api/v1/spells/list")).json() as Array<{ id: number; name: string }>;
  const ids = new Map(list.map((entry) => [entry.name.toLowerCase().replace(/\s+rune$/, ""), entry.id]));
  const result = [];
  for (const spell of EXISTING_SPELLS) {
    if (spell.type !== "rune") { result.push({ ...spell, description: null, cooldownSeconds: null, groupCooldownSeconds: null, soulPoints: null, amount: null, runeVocations: [], runeGroup: null, runeRequiredLevel: null, runeMagicLevel: null }); continue; }
    const id = ids.get(spell.name.toLowerCase().replace(/\s+rune$/, ""));
    if (id === undefined) { result.push({ ...spell, description: null, cooldownSeconds: null, groupCooldownSeconds: null, soulPoints: null, amount: null, runeVocations: [], runeGroup: null, runeRequiredLevel: spell.requiredLevel, runeMagicLevel: null }); continue; }
    const detail = await (await fetch(`https://tibiadata.bytewizards.de/api/v1/spells/${id}`)).json();
    result.push({ ...spell, ...parseCommunitySpellDetail(detail, spell) });
  }
  return result;
}
