// Generated by npm run skills:sync. Do not edit manually.
// Official source: https://www.tibia.com/library/?subtopic=spells
// Generated at: 2026-08-03T23:28:38.396Z
import type { TibiaSpellCatalogEntry } from "./tibia-spell-catalog.js";

export const TIBIA_SPELL_CATALOG_GENERATED_AT = "2026-08-03T23:28:38.396Z";
export const TIBIA_SPELL_CATALOG_SOURCE = "https://www.tibia.com/library/?subtopic=spells";
export const TIBIA_SPELL_CATALOG = [
  {
    "id": "animatedeadrune",
    "name": "Animate Dead Rune",
    "words": "adana mort",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 600,
    "manaText": "600",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "annihilation",
    "name": "Annihilation",
    "words": "exori gran ico",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 110,
    "manaCost": 300,
    "manaText": "300",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "apprenticestrike",
    "name": "Apprentice's Strike",
    "words": "exori min flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 6,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "arrowcall",
    "name": "Arrow Call",
    "words": "exevo infir con",
    "group": "support",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 30,
    "manaText": "30",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "exposeweakness",
    "name": "Aura of Exposed Weakness",
    "words": "exori moe tempo",
    "group": "support",
    "type": "instant",
    "requiredLevel": 175,
    "manaCost": 1500,
    "manaText": "1500",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "sapstrength",
    "name": "Aura of Sapped Strength",
    "words": "exori kor tempo",
    "group": "support",
    "type": "instant",
    "requiredLevel": 175,
    "manaCost": 1500,
    "manaText": "1500",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "avalancherune",
    "name": "Avalanche Rune",
    "words": "adori mas frigo",
    "group": "support",
    "type": "rune",
    "requiredLevel": 30,
    "manaCost": 530,
    "manaText": "530",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "avatarofbalance",
    "name": "Avatar of Balance",
    "words": "uteta res tio",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 1200,
    "manaText": "1200",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "avataroflight",
    "name": "Avatar of Light",
    "words": "uteta res sac",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 1500,
    "manaText": "1500",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "avatarofnature",
    "name": "Avatar of Nature",
    "words": "uteta res dru",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 2200,
    "manaText": "2200",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "avatarofsteel",
    "name": "Avatar of Steel",
    "words": "uteta res eq",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 800,
    "manaText": "800",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "avatarofstorm",
    "name": "Avatar of Storm",
    "words": "uteta res ven",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 2200,
    "manaText": "2200",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "balancedbrawl",
    "name": "Balanced Brawl",
    "words": "exori mas res",
    "group": "support",
    "type": "instant",
    "requiredLevel": 175,
    "manaCost": 80,
    "manaText": "80",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "berserk",
    "name": "Berserk",
    "words": "exori",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 35,
    "manaCost": 125,
    "manaText": "125",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "bloodrage",
    "name": "Blood Rage",
    "words": "utito tempo",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 20,
    "manaText": "20",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "bruisebane",
    "name": "Bruise Bane",
    "words": "exura infir ico",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 10,
    "manaText": "10",
    "premium": false,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "brutalstrike",
    "name": "Brutal Strike",
    "words": "exori ico",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 16,
    "manaCost": 30,
    "manaText": "30",
    "premium": false,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "buzz",
    "name": "Buzz",
    "words": "exori infir vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "cancelinvisibility",
    "name": "Cancel Invisibility",
    "words": "exana ina",
    "group": "support",
    "type": "instant",
    "requiredLevel": 26,
    "manaCost": 200,
    "manaText": "200",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "cancelmagicshield",
    "name": "Cancel Magic Shield",
    "words": "exana vita",
    "group": "support",
    "type": "instant",
    "requiredLevel": 14,
    "manaCost": 50,
    "manaText": "50",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "chainedpenance",
    "name": "Chained Penance",
    "words": "exori med pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 180,
    "manaText": "180",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "challenge",
    "name": "Challenge",
    "words": "exeta res",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 40,
    "manaText": "40",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "chameleonrune",
    "name": "Chameleon Rune",
    "words": "adevo ina",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 600,
    "manaText": "600",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "charge",
    "name": "Charge",
    "words": "utani tempo hur",
    "group": "support",
    "type": "instant",
    "requiredLevel": 25,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "chillout",
    "name": "Chill Out",
    "words": "exevo infir frigo hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 8,
    "manaText": "8",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "chivalrouschallenge",
    "name": "Chivalrous Challenge",
    "words": "exeta amp res",
    "group": "support",
    "type": "instant",
    "requiredLevel": 150,
    "manaCost": 80,
    "manaText": "80",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "conjurearrow",
    "name": "Conjure Arrow",
    "words": "exevo con",
    "group": "support",
    "type": "instant",
    "requiredLevel": 13,
    "manaCost": 100,
    "manaText": "100",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "conjureexplosivearrow",
    "name": "Conjure Explosive Arrow",
    "words": "exevo con flam",
    "group": "support",
    "type": "instant",
    "requiredLevel": 25,
    "manaCost": 290,
    "manaText": "290",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "conjurewandofdarkness",
    "name": "Conjure Wand of Darkness",
    "words": "exevo gran mort",
    "group": "support",
    "type": "instant",
    "requiredLevel": 41,
    "manaCost": 250,
    "manaText": "250",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "convincecreaturerune",
    "name": "Convince Creature Rune",
    "words": "adeta sio",
    "group": "support",
    "type": "rune",
    "requiredLevel": 16,
    "manaCost": 200,
    "manaText": "200",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "creatureillusion",
    "name": "Creature Illusion",
    "words": "utevo res ina \"creature\"",
    "group": "support",
    "type": "instant",
    "requiredLevel": 23,
    "manaCost": 100,
    "manaText": "100",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "curebleeding",
    "name": "Cure Bleeding",
    "words": "exana kor",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 45,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "druid",
      "knight"
    ]
  },
  {
    "id": "cureburning",
    "name": "Cure Burning",
    "words": "exana flam",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 30,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "curecurse",
    "name": "Cure Curse",
    "words": "exana mort",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 40,
    "manaText": "40",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "cureelectrification",
    "name": "Cure Electrification",
    "words": "exana vis",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 22,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "curepoison",
    "name": "Cure Poison",
    "words": "exana pox",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 10,
    "manaCost": 30,
    "manaText": "30",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "curepoisonrune",
    "name": "Cure Poison Rune",
    "words": "adana pox",
    "group": "support",
    "type": "rune",
    "requiredLevel": 15,
    "manaCost": 200,
    "manaText": "200",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "curse",
    "name": "Curse",
    "words": "utori mort",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 75,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "deathecho",
    "name": "Death Echo",
    "words": "exevo mort ora",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 120,
    "manaCost": 150,
    "manaText": "150",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "deathstrike",
    "name": "Death Strike",
    "words": "exori mort",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 16,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "destroyfieldrune",
    "name": "Destroy Field Rune",
    "words": "adito grav",
    "group": "support",
    "type": "rune",
    "requiredLevel": 17,
    "manaCost": 120,
    "manaText": "120",
    "premium": false,
    "vocations": [
      "druid",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "devastatingknockout",
    "name": "Devastating Knockout",
    "words": "exori gran nia",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 125,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "disintegraterune",
    "name": "Disintegrate Rune",
    "words": "adito tera",
    "group": "support",
    "type": "rune",
    "requiredLevel": 21,
    "manaCost": 200,
    "manaText": "200",
    "premium": true,
    "vocations": [
      "druid",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "divinebarrage",
    "name": "Divine Barrage",
    "words": "exori dir san",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 175,
    "manaText": "175",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinecaldera",
    "name": "Divine Caldera",
    "words": "exevo mas san",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 50,
    "manaCost": 160,
    "manaText": "160",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinedazzle",
    "name": "Divine Dazzle",
    "words": "exana amp res",
    "group": "support",
    "type": "instant",
    "requiredLevel": 250,
    "manaCost": 80,
    "manaText": "80",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinedefiance",
    "name": "Divine Defiance",
    "words": "utori hur",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 250,
    "manaText": "250",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divineempowerment",
    "name": "Divine Empowerment",
    "words": "utevo grav san",
    "group": "support",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 500,
    "manaText": "500",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinegrenade",
    "name": "Divine Grenade",
    "words": "exevo tempo mas san",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 160,
    "manaText": "160",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinehealing",
    "name": "Divine Healing",
    "words": "exura san",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 35,
    "manaCost": 160,
    "manaText": "160",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "divinemissile",
    "name": "Divine Missile",
    "words": "exori san",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 40,
    "manaCost": 20,
    "manaText": "20",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "doublejab",
    "name": "Double Jab",
    "words": "exori pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 14,
    "manaCost": 30,
    "manaText": "30",
    "premium": false,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "electrify",
    "name": "Electrify",
    "words": "utori vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 34,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "elementalsynthesis",
    "name": "Elemental Synthesis",
    "words": "utito dru",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "enchantparty",
    "name": "Enchant Party",
    "words": "utori mas sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 32,
    "manaCost": null,
    "manaText": "var.",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "enchantspear",
    "name": "Enchant Spear",
    "words": "exeta con",
    "group": "support",
    "type": "instant",
    "requiredLevel": 45,
    "manaCost": 350,
    "manaText": "350",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "energybeam",
    "name": "Energy Beam",
    "words": "exevo vis lux",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 23,
    "manaCost": 40,
    "manaText": "40",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "energybombrune",
    "name": "Energy Bomb Rune",
    "words": "adevo mas vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 37,
    "manaCost": 880,
    "manaText": "880",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "energyfieldrune",
    "name": "Energy Field Rune",
    "words": "adevo grav vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 18,
    "manaCost": 320,
    "manaText": "320",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "energystrike",
    "name": "Energy Strike",
    "words": "exori vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 12,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "energywallrune",
    "name": "Energy Wall Rune",
    "words": "adevo mas grav vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 41,
    "manaCost": 1000,
    "manaText": "1000",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "energywave",
    "name": "Energy Wave",
    "words": "exevo vis hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 38,
    "manaCost": 170,
    "manaText": "170",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "enlightenparty",
    "name": "Enlighten Party",
    "words": "utevo mas sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 32,
    "manaCost": 75,
    "manaText": "75",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "envenom",
    "name": "Envenom",
    "words": "utori pox",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 50,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "eternalwinter",
    "name": "Eternal Winter",
    "words": "exevo gran mas frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 60,
    "manaCost": 1050,
    "manaText": "1050",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "etherealbarrage",
    "name": "Ethereal Barrage",
    "words": "exori dir moe",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 60,
    "manaCost": 135,
    "manaText": "135",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "etherealspear",
    "name": "Ethereal Spear",
    "words": "exori con",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 23,
    "manaCost": 25,
    "manaText": "25",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "executionersthrow",
    "name": "Executioner's Throw",
    "words": "exori amp kor",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 225,
    "manaText": "225",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "explosionrune",
    "name": "Explosion Rune",
    "words": "adevo mas hur",
    "group": "support",
    "type": "rune",
    "requiredLevel": 31,
    "manaCost": 570,
    "manaText": "570",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "fairwoundcleansing",
    "name": "Fair Wound Cleansing",
    "words": "exura med ico",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 300,
    "manaCost": 135,
    "manaText": "135",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "fierceberserk",
    "name": "Fierce Berserk",
    "words": "exori gran",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 360,
    "manaText": "360",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "findfiend",
    "name": "Find Fiend",
    "words": "exiva moe res",
    "group": "support",
    "type": "instant",
    "requiredLevel": 25,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "findperson",
    "name": "Find Person",
    "words": "exiva \"name\"",
    "group": "support",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "firebombrune",
    "name": "Fire Bomb Rune",
    "words": "adevo mas flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 600,
    "manaText": "600",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "firefieldrune",
    "name": "Fire Field Rune",
    "words": "adevo grav flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 15,
    "manaCost": 240,
    "manaText": "240",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "firewallrune",
    "name": "Fire Wall Rune",
    "words": "adevo mas grav flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 33,
    "manaCost": 780,
    "manaText": "780",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "firewave",
    "name": "Fire Wave",
    "words": "exevo flam hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 25,
    "manaText": "25",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "fireballrune",
    "name": "Fireball Rune",
    "words": "adori flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 460,
    "manaText": "460",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "flamestrike",
    "name": "Flame Strike",
    "words": "exori flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "flurryofblows",
    "name": "Flurry of Blows",
    "words": "exori mas pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 35,
    "manaCost": 110,
    "manaText": "110",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "focusharmony",
    "name": "Focus Harmony",
    "words": "utevo nia",
    "group": "support",
    "type": "instant",
    "requiredLevel": 275,
    "manaCost": 500,
    "manaText": "500",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "focusserenity",
    "name": "Focus Serenity",
    "words": "utamo tio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 150,
    "manaCost": 500,
    "manaText": "500",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "food",
    "name": "Food",
    "words": "exevo pan",
    "group": "support",
    "type": "instant",
    "requiredLevel": 14,
    "manaCost": 120,
    "manaText": "120",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "forcefuluppercut",
    "name": "Forceful Uppercut",
    "words": "exori gran pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 110,
    "manaCost": 325,
    "manaText": "325",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "forkedglacier",
    "name": "Forked Glacier",
    "words": "exevo fur frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 180,
    "manaText": "180",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "forkedthorns",
    "name": "Forked Thorns",
    "words": "exevo fur tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 180,
    "manaText": "180",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "frontsweep",
    "name": "Front Sweep",
    "words": "exori min",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 200,
    "manaText": "200",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "greatdeathbeam",
    "name": "Great Death Beam",
    "words": "exevo max mort",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 66,
    "manaCost": 140,
    "manaText": "140",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "greatenergybeam",
    "name": "Great Energy Beam",
    "words": "exevo gran vis lux",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 29,
    "manaCost": 110,
    "manaText": "110",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "greatfirewave",
    "name": "Great Fire Wave",
    "words": "exevo gran flam hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 38,
    "manaCost": 120,
    "manaText": "120",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "greatfireballrune",
    "name": "Great Fireball Rune",
    "words": "adori mas flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 30,
    "manaCost": 530,
    "manaText": "530",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "greatlight",
    "name": "Great Light",
    "words": "utevo gran lux",
    "group": "support",
    "type": "instant",
    "requiredLevel": 13,
    "manaCost": 60,
    "manaText": "60",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "greaterflurryofblows",
    "name": "Greater Flurry of Blows",
    "words": "exori gran mas pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 300,
    "manaText": "300",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "greatertigerclash",
    "name": "Greater Tiger Clash",
    "words": "exori nia",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 50,
    "manaText": "50",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "groundshaker",
    "name": "Groundshaker",
    "words": "exori mas",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 33,
    "manaCost": 200,
    "manaText": "200",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "haste",
    "name": "Haste",
    "words": "utani hur",
    "group": "support",
    "type": "instant",
    "requiredLevel": 14,
    "manaCost": 60,
    "manaText": "60",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "healfriend",
    "name": "Heal Friend",
    "words": "exura sio \"name\"",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 120,
    "manaText": "120",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "healparty",
    "name": "Heal Party",
    "words": "utura mas sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 32,
    "manaCost": null,
    "manaText": "var.",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "heavymagicmissilerune",
    "name": "Heavy Magic Missile Rune",
    "words": "adori vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 25,
    "manaCost": 350,
    "manaText": "350",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "hellscore",
    "name": "Hell's Core",
    "words": "exevo gran mas flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 60,
    "manaCost": 1100,
    "manaText": "1100",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "holyflash",
    "name": "Holy Flash",
    "words": "utori san",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "holymissilerune",
    "name": "Holy Missile Rune",
    "words": "adori san",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 300,
    "manaText": "300",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "iceburst",
    "name": "Ice Burst",
    "words": "exevo ulus frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 230,
    "manaText": "230",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "icestrike",
    "name": "Ice Strike",
    "words": "exori frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "icewave",
    "name": "Ice Wave",
    "words": "exevo frigo hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 25,
    "manaText": "25",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "iciclerune",
    "name": "Icicle Rune",
    "words": "adori frigo",
    "group": "support",
    "type": "rune",
    "requiredLevel": 28,
    "manaCost": 460,
    "manaText": "460",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "ignite",
    "name": "Ignite",
    "words": "utori flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 26,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "inflictwound",
    "name": "Inflict Wound",
    "words": "utori kor",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 40,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "knight",
      "monk"
    ]
  },
  {
    "id": "intensehealing",
    "name": "Intense Healing",
    "words": "exura gran",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 70,
    "manaText": "70",
    "premium": false,
    "vocations": [
      "druid",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "intensehealingrune",
    "name": "Intense Healing Rune",
    "words": "adura gran",
    "group": "support",
    "type": "rune",
    "requiredLevel": 15,
    "manaCost": 120,
    "manaText": "120",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "intenserecovery",
    "name": "Intense Recovery",
    "words": "utura gran",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 100,
    "manaCost": 165,
    "manaText": "165",
    "premium": true,
    "vocations": [
      "knight",
      "paladin"
    ]
  },
  {
    "id": "intensewoundcleansing",
    "name": "Intense Wound Cleansing",
    "words": "exura gran ico",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 300,
    "manaText": "300",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "invisible",
    "name": "Invisible",
    "words": "utana vid",
    "group": "support",
    "type": "instant",
    "requiredLevel": 35,
    "manaCost": 440,
    "manaText": "440",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "lesseretherealspear",
    "name": "Lesser Ethereal Spear",
    "words": "exori infir con",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "lesserfrontsweep",
    "name": "Lesser Front Sweep",
    "words": "exori infir min",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "lessermysticrepulse",
    "name": "Lesser Mystic Repulse",
    "words": "exori infir amp pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 6,
    "manaCost": 30,
    "manaText": "30",
    "premium": false,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "levitate",
    "name": "Levitate",
    "words": "exani hur \"up|down\"",
    "group": "support",
    "type": "instant",
    "requiredLevel": 12,
    "manaCost": 50,
    "manaText": "50",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "light",
    "name": "Light",
    "words": "utevo lux",
    "group": "support",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "lighthealing",
    "name": "Light Healing",
    "words": "exura",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "lightmagicmissilerune",
    "name": "Light Magic Missile Rune",
    "words": "adori min vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 15,
    "manaCost": 120,
    "manaText": "120",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "lightning",
    "name": "Lightning",
    "words": "exori amp vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 55,
    "manaCost": 60,
    "manaText": "60",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "magicpatch",
    "name": "Magic Patch",
    "words": "exura infir",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "druid",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "magicrope",
    "name": "Magic Rope",
    "words": "exani tera",
    "group": "support",
    "type": "instant",
    "requiredLevel": 9,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "knight",
      "paladin",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "magicshield",
    "name": "Magic Shield",
    "words": "utamo vita",
    "group": "support",
    "type": "instant",
    "requiredLevel": 14,
    "manaCost": 50,
    "manaText": "50",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "magicwallrune",
    "name": "Magic Wall Rune",
    "words": "adevo grav tera",
    "group": "support",
    "type": "rune",
    "requiredLevel": 32,
    "manaCost": 750,
    "manaText": "750",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "masshealing",
    "name": "Mass Healing",
    "words": "exura gran mas res",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 36,
    "manaCost": 150,
    "manaText": "150",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "massspiritmend",
    "name": "Mass Spirit Mend",
    "words": "exura mas nia",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 150,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "masterofdecay",
    "name": "Master of Decay",
    "words": "uteta mort",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "masterofflames",
    "name": "Master of Flames",
    "words": "uteta flam",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "masterofthunder",
    "name": "Master of Thunder",
    "words": "uteta vis",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "mudattack",
    "name": "Mud Attack",
    "words": "exori infir tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 6,
    "manaText": "6",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "mysticrepulse",
    "name": "Mystic Repulse",
    "words": "exori amp pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 30,
    "manaCost": 150,
    "manaText": "150",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "naturesembrace",
    "name": "Nature's Embrace",
    "words": "exura gran sio \"name\"",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 275,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "paralyserune",
    "name": "Paralyse Rune",
    "words": "adana ani",
    "group": "support",
    "type": "rune",
    "requiredLevel": 54,
    "manaCost": 1400,
    "manaText": "1400",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "physicalstrike",
    "name": "Physical Strike",
    "words": "exori moe ico",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 16,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "poisonbombrune",
    "name": "Poison Bomb Rune",
    "words": "adevo mas pox",
    "group": "support",
    "type": "rune",
    "requiredLevel": 25,
    "manaCost": 520,
    "manaText": "520",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "poisonfieldrune",
    "name": "Poison Field Rune",
    "words": "adevo grav pox",
    "group": "support",
    "type": "rune",
    "requiredLevel": 14,
    "manaCost": 200,
    "manaText": "200",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "poisonwallrune",
    "name": "Poison Wall Rune",
    "words": "adevo mas grav pox",
    "group": "support",
    "type": "rune",
    "requiredLevel": 29,
    "manaCost": 640,
    "manaText": "640",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "protectparty",
    "name": "Protect Party",
    "words": "utamo mas sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 32,
    "manaCost": null,
    "manaText": "var.",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "protector",
    "name": "Protector",
    "words": "utamo tempo",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 20,
    "manaText": "20",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "rageoftheskies",
    "name": "Rage of the Skies",
    "words": "exevo gran mas vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 55,
    "manaCost": 600,
    "manaText": "600",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "recovery",
    "name": "Recovery",
    "words": "utura",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 50,
    "manaCost": 75,
    "manaText": "75",
    "premium": true,
    "vocations": [
      "knight",
      "paladin"
    ]
  },
  {
    "id": "restoration",
    "name": "Restoration",
    "words": "exura max vita",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 300,
    "manaCost": 260,
    "manaText": "260",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "restorebalance",
    "name": "Restore Balance",
    "words": "exura tio sio \"name\"",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 120,
    "manaText": "120",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "salvation",
    "name": "Salvation",
    "words": "exura gran san",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 60,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "scorch",
    "name": "Scorch",
    "words": "exevo infir flam hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 1,
    "manaCost": 8,
    "manaText": "8",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "sharedconservation",
    "name": "Shared Conservation",
    "words": "utura sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "sharpshooter",
    "name": "Sharpshooter",
    "words": "utori con",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 250,
    "manaText": "250",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "shieldbash",
    "name": "Shield Bash",
    "words": "exori ico scu",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 18,
    "manaCost": 30,
    "manaText": "30",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "shieldslam",
    "name": "Shield Slam",
    "words": "exori scu",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 30,
    "manaCost": 110,
    "manaText": "110",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "soulfirerune",
    "name": "Soulfire Rune",
    "words": "adevo res flam",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 420,
    "manaText": "420",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "spiritmend",
    "name": "Spirit Mend",
    "words": "exura gran tio",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "spiritualoutburst",
    "name": "Spiritual Outburst",
    "words": "exori gran mas nia",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 425,
    "manaText": "425",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "stalagmiterune",
    "name": "Stalagmite Rune",
    "words": "adori tera",
    "group": "support",
    "type": "rune",
    "requiredLevel": 24,
    "manaCost": 350,
    "manaText": "350",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "stoneshowerrune",
    "name": "Stone Shower Rune",
    "words": "adori mas tera",
    "group": "support",
    "type": "rune",
    "requiredLevel": 28,
    "manaCost": 430,
    "manaText": "430",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "strongenergystrike",
    "name": "Strong Energy Strike",
    "words": "exori gran vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 60,
    "manaText": "60",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "strongetherealspear",
    "name": "Strong Ethereal Spear",
    "words": "exori gran con",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 55,
    "manaText": "55",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "strongflamestrike",
    "name": "Strong Flame Strike",
    "words": "exori gran flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 60,
    "manaText": "60",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "stronghaste",
    "name": "Strong Haste",
    "words": "utani gran hur",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer",
      "monk"
    ]
  },
  {
    "id": "strongicestrike",
    "name": "Strong Ice Strike",
    "words": "exori gran frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 80,
    "manaCost": 60,
    "manaText": "60",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "strongicewave",
    "name": "Strong Ice Wave",
    "words": "exevo gran frigo hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 40,
    "manaCost": 170,
    "manaText": "170",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "strongterrastrike",
    "name": "Strong Terra Strike",
    "words": "exori gran tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 70,
    "manaCost": 60,
    "manaText": "60",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "suddendeathrune",
    "name": "Sudden Death Rune",
    "words": "adori gran mort",
    "group": "support",
    "type": "rune",
    "requiredLevel": 45,
    "manaCost": 985,
    "manaText": "985",
    "premium": false,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "summoncreature",
    "name": "Summon Creature",
    "words": "utevo res \"creature\"",
    "group": "support",
    "type": "instant",
    "requiredLevel": 25,
    "manaCost": null,
    "manaText": "var.",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "summondruid",
    "name": "Summon Druid Familiar",
    "words": "utevo gran res dru",
    "group": "support",
    "type": "instant",
    "requiredLevel": 200,
    "manaCost": 3000,
    "manaText": "3000",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "summonknight",
    "name": "Summon Knight Familiar",
    "words": "utevo gran res eq",
    "group": "support",
    "type": "instant",
    "requiredLevel": 200,
    "manaCost": 1000,
    "manaText": "1000",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "summonmonkfamiliar",
    "name": "Summon Monk Familiar",
    "words": "utevo gran res tio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 200,
    "manaCost": 1500,
    "manaText": "1500",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "summonpaladin",
    "name": "Summon Paladin Familiar",
    "words": "utevo gran res sac",
    "group": "support",
    "type": "instant",
    "requiredLevel": 200,
    "manaCost": 2000,
    "manaText": "2000",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "summonsorcerer",
    "name": "Summon Sorcerer Familiar",
    "words": "utevo gran res ven",
    "group": "support",
    "type": "instant",
    "requiredLevel": 200,
    "manaCost": 3000,
    "manaText": "3000",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "sweepingtakedown",
    "name": "Sweeping Takedown",
    "words": "exori mas nia",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 60,
    "manaCost": 195,
    "manaText": "195",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "swiftfoot",
    "name": "Swift Foot",
    "words": "utamo tempo san",
    "group": "support",
    "type": "instant",
    "requiredLevel": 55,
    "manaCost": 400,
    "manaText": "400",
    "premium": true,
    "vocations": [
      "paladin"
    ]
  },
  {
    "id": "swiftjab",
    "name": "Swift Jab",
    "words": "exori infir pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 3,
    "manaText": "3",
    "premium": false,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "terraburst",
    "name": "Terra Burst",
    "words": "exevo ulus tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 230,
    "manaText": "230",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "terrastrike",
    "name": "Terra Strike",
    "words": "exori tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 13,
    "manaCost": 20,
    "manaText": "20",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "terrawave",
    "name": "Terra Wave",
    "words": "exevo tera hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 38,
    "manaCost": 170,
    "manaText": "170",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "thousandfistblow",
    "name": "Thousand Fist Blows",
    "words": "exori mas amp pug",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 120,
    "manaCost": 145,
    "manaText": "145",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "thunderstormrune",
    "name": "Thunderstorm Rune",
    "words": "adori mas vis",
    "group": "support",
    "type": "rune",
    "requiredLevel": 28,
    "manaCost": 430,
    "manaText": "430",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "tigerclash",
    "name": "Tiger Clash",
    "words": "exori infir nia",
    "group": "attack",
    "type": "instant",
    "requiredLevel": null,
    "manaCost": 18,
    "manaText": "18",
    "premium": false,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "trainparty",
    "name": "Train Party",
    "words": "utito mas sio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 32,
    "manaCost": null,
    "manaText": "var.",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "ultimateenergystrike",
    "name": "Ultimate Energy Strike",
    "words": "exori max vis",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 100,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "ultimateflamestrike",
    "name": "Ultimate Flame Strike",
    "words": "exori max flam",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "sorcerer"
    ]
  },
  {
    "id": "ultimatehealing",
    "name": "Ultimate Healing",
    "words": "exura vita",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 30,
    "manaCost": 160,
    "manaText": "160",
    "premium": false,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "ultimatehealingrune",
    "name": "Ultimate Healing Rune",
    "words": "adura vita",
    "group": "support",
    "type": "rune",
    "requiredLevel": 24,
    "manaCost": 400,
    "manaText": "400",
    "premium": false,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "ultimateicestrike",
    "name": "Ultimate Ice Strike",
    "words": "exori max frigo",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 100,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "ultimatelight",
    "name": "Ultimate Light",
    "words": "utevo vis lux",
    "group": "support",
    "type": "instant",
    "requiredLevel": 26,
    "manaCost": 140,
    "manaText": "140",
    "premium": true,
    "vocations": [
      "druid",
      "sorcerer"
    ]
  },
  {
    "id": "ultimateterrastrike",
    "name": "Ultimate Terra Strike",
    "words": "exori max tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 90,
    "manaCost": 100,
    "manaText": "100",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "virtueofharmony",
    "name": "Virtue of Harmony",
    "words": "utori virtu",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "virtueofjustice",
    "name": "Virtue of Justice",
    "words": "utito virtu",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "virtueofsustain",
    "name": "Virtue of Sustain",
    "words": "utura tio",
    "group": "support",
    "type": "instant",
    "requiredLevel": 20,
    "manaCost": 210,
    "manaText": "210",
    "premium": true,
    "vocations": [
      "monk"
    ]
  },
  {
    "id": "whirlwindthrow",
    "name": "Whirlwind Throw",
    "words": "exori hur",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 28,
    "manaCost": 40,
    "manaText": "40",
    "premium": true,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "wildgrowthrune",
    "name": "Wild Growth Rune",
    "words": "adevo grav vita",
    "group": "support",
    "type": "rune",
    "requiredLevel": 27,
    "manaCost": 600,
    "manaText": "600",
    "premium": true,
    "vocations": [
      "druid"
    ]
  },
  {
    "id": "woundcleansing",
    "name": "Wound Cleansing",
    "words": "exura ico",
    "group": "healing",
    "type": "instant",
    "requiredLevel": 8,
    "manaCost": 60,
    "manaText": "60",
    "premium": false,
    "vocations": [
      "knight"
    ]
  },
  {
    "id": "wrathofnature",
    "name": "Wrath of Nature",
    "words": "exevo gran mas tera",
    "group": "attack",
    "type": "instant",
    "requiredLevel": 55,
    "manaCost": 700,
    "manaText": "700",
    "premium": true,
    "vocations": [
      "druid"
    ]
  }
] as const satisfies readonly TibiaSpellCatalogEntry[];
